#!/bin/bash

# bash script to automatically execute the go file for respective day
# provided in the command line argument

# Check if an argument is provided
if [ -z "$1" ]; then
	$(echo "Usage: ./make.sh <day>" 1>&2)
    exit 1
fi

# Construct the filename based on the input number
filename="day$1.go"

# Run if file exists
if [ -f "$filename" ]; then
	go run "$filename"
else
	$(echo "Error: $filename not found.")
fi

